//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace babynophone.App.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("babynophone.App.Resources.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the communication.
        /// </summary>
        internal static string ChooseContactButton {
            get {
                return ResourceManager.GetString("ChooseContactButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noise level.
        /// </summary>
        internal static string ChooseNoiseLevelButton {
            get {
                return ResourceManager.GetString("ChooseNoiseLevelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter the skype user you want to call to.
        /// </summary>
        internal static string ChooseSkypeUserLabel {
            get {
                return ResourceManager.GetString("ChooseSkypeUserLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string ChooseSkypeUserOKButton {
            get {
                return ResourceManager.GetString("ChooseSkypeUserOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please choose.
        /// </summary>
        internal static string PleaseChooseLabel {
            get {
                return ResourceManager.GetString("PleaseChooseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skype is not installed.
        /// </summary>
        internal static string SkypeIsNotInstalledText1 {
            get {
                return ResourceManager.GetString("SkypeIsNotInstalledText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start.
        /// </summary>
        internal static string StartStopButtonStart {
            get {
                return ResourceManager.GetString("StartStopButtonStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop.
        /// </summary>
        internal static string StartStopButtonStop {
            get {
                return ResourceManager.GetString("StartStopButtonStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enable video.
        /// </summary>
        internal static string UseVideoLabel {
            get {
                return ResourceManager.GetString("UseVideoLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to you are using.
        /// </summary>
        internal static string YouAreUsingLabel {
            get {
                return ResourceManager.GetString("YouAreUsingLabel", resourceCulture);
            }
        }
    }
}
